name: Run Crawler every 2h

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Call /admin/run-crawler
        run: |
          set -e
          URL="https://DEIN-SERVICE.onrender.com/admin/run-crawler?token=${{ secrets.RUN_TOKEN }}&limit=50"
          CODE=$(curl -sS -o resp.json -w "%{http_code}" -X POST "$URL")
          echo "HTTP $CODE"
          cat resp.json || true
          test "$CODE" = "200"
